### ISSUE TITLE
Router.crt

### ISSUE THREAD

**Issue by Zhang-Haoran** [matthew1471/EdgeOS-API#2]
Hi Matthew, 
I have a few questions when I was using this API. Could you help me to figure it out?
1. What is 'router.crt' file in the InterfaceChart.csproj? 
2. How can I get it from my router? 
 
Thank you!@matthew1471

**Comment by Matthew1471** [comment]
Hi @Zhang-Haoran  :-)

You simply need to save the certificate your router has generated by visiting it in a web-browser of your choice and choosing the functionality to save the certificate to a file.

There's some guides here : https://medium.com/@menakajain/export-download-ssl-certificate-from-server-site-url-bcfc41ea46a2
